package com.mss;
// Generated Apr 11, 2016 9:54:14 AM by Hibernate Tools 4.3.1



/**
 * Auth generated by hbm2java
 */
public class Auth  implements java.io.Serializable {


     private String username;
     private String password;

    public Auth() {
    }

	
    public Auth(String username) {
        this.username = username;
    }
    public Auth(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


